meta_product_name: "Ateliers - Celine"
meta_title: "Ateliers Celine - Inspired by Traditions, Crafted by you"
meta_description: "Ateliers Celine has curated workshop experiences led by expert artisan makers to nourish the creative soul. Our Artisan Workshops Kits."
meta_image: "cover.png" # should exist in `app/assets/images/`